version: '3'

services:
  payservice:
     build: .
     container_name: payservice_app
     volumes:
       - .:/go/src
     ports:
       - "8080:8080"

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306  
    volumes:
      - .docker/mysql:/var/lib/mysql