// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Balance struct {
	ID        string
	UserID    string
	Amount    sql.NullString
	CreatedAt time.Time
}
