// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: query.sql

package db

import (
	"context"
)

const getBalanceByAccountID = `-- name: GetBalanceByAccountID :one
select amount from balances where user_id = ?
`

func (q *Queries) GetBalanceByAccountID(ctx context.Context, userID string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getBalanceByAccountID, userID)
	var amount float64
	err := row.Scan(&amount)
	return amount, err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE balances SET amount = ? WHERE user_id = ?
`

type UpdateBalanceParams struct {
	Amount float64
	UserID string
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateBalance, arg.Amount, arg.UserID)
	return err
}
